env:
    token: "ENCRYPTED[4c835ba91115dcdca93463678d8ef3bf8b2f741a72acf6e038b341dca4ca76eedca6b611947e623dcf251448cff049d1]"
    chat_id: "ENCRYPTED[9edb2aae69df938d569c91bcc992b8b3ad3570cbb2fdb861c9d9bb160f8f546b8115c06cb869b7f1bc2c49348adcacb8]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: ubuntu:devel
      cpu: 8
      memory: 32G

  Build_script:
      - apt update && apt upgrade -y
      - ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
      - apt install -f -y git bison flex libxml2 locales libssl-dev bc zip default-jre python3 python3-pip wget curl dpkg cpio bash python2
      - locale-gen en_US en_US.UTF-8
      - dpkg-reconfigure locales
      - git clone --depth=1 https://github.com/reaPeR1010/android_kernel_motorola_sanders XD && cd XD
      - bash build.sh --atomx --lld --oc
